config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  root 'posts#index'

  get 'password_resets/new'
  resources :password_resets

  resources :posts do
    resources :comments do
      resources :votes
      post '/dislikes' => 'votes#dislike', as: :dislike_create
    end
  end

  resources :authors do
    member do
      get :confirm_email
    end
  end
  resources :sessions, only: %i[new create destroy]
  get 'signup', to: 'authors#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
end
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :author
  has_many :votes, dependent: :destroy
  has_ancestry orphan_strategy: :adopt
  validates :body, presence: true
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :correct_author, only: %i[edit update destroy new]
  before_action :hour_for_comment_editing, only: %i[edit update]
  before_action :banned?, only: %i[new create]

  def correct_author
    @comment = Post.find(params[:post_id])
    redirect_to root_path(current_author) unless current_author
  end

  def hour_for_comment_editing
    Time.now - @comment.created_at < 3600
  end

  def new
    @post = Post.find(params[:post_id])
    @comment = Comment.new(parent_id: params[:parent_id])
  end

  def edit
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    respond_to do |format|
      format.js { render 'edit', status: :created, location: @post }
      flash[:success] = 'Comment successfully edited'
    end
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    @comment.author_id = current_author.id
    if @comment.ancestors.count <= 4
      respond_to do |format|
        if @comment.save
          format.js { render 'create', status: :created, location: @post }
          flash[:success] = 'Comment was successfully created.'
        else
          flash[:danger] = @comment.errors.full_messages.first
        end
      end
    else
      respond_to do |_format|
        flash[:warning] = 'To much comments in one tree (5 comments max)'
      end
    end
  end

  def update
    @comment = Comment.find(params[:id])
    @post = Post.find(params[:post_id])
    respond_to do |format|
      if @comment.update(comment_params)
        format.js { render 'update', status: :created, location: @post }
        flash[:success] = 'Comment was successfully updated.'
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    if current_author.id == @comment.author_id
      @comment.destroy
      respond_to do |format|
        format.js { render 'destroy', status: :created, location: @post }
        format.html { redirect_to @post, notice: 'Comment was successfully destroyed.' }
      end
    else
      redirect_to root_path
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :author_id, :parent_id)
  end
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
  def count_rating(sample)
    sample.where(count: 1).count - sample.where(count: -1).count
  end
end

app/views/comments/_comment.html.erb
  <div class="comment<%= comment.id %>">
    <p><strong><%= comment.author.login %></strong>:<%= comment.body %></p>
    <small> <% if edited?(comment) %>
            <p>edited <%= fa_icon 'edit'%> </p>
            <% end %></small>
    <small data-toggle="tooltip" data-placement="top" title="(<%=comment.updated_at  %>)"><time><%= time_ago_in_words(comment.created_at) %> ago</time ></small>
      <% if current_author %>
      <%= link_to "Reply", new_post_comment_path(comment.post, :parent_id => comment.id), id: 'comment_reply_link', remote: true,  class:'btn btn-outline-primary' %>
      <% pre_vote = comment.votes.find { |vote| vote.author_id == current_author.id} %>
      <% if current_author %>
            <% pre_vote = comment.votes.find { |vote| vote.author_id == current_author.id} %>
          <% end %>
          <% if current_author and pre_vote == nil %>
            <%= link_to '↑', post_comment_votes_path(@post, comment), remote: true, method: :post, class: 'btn btn-success ' %>
            <strong><%= count_rating(comment.votes)%></strong>
            <%= link_to '↓', post_comment_dislike_create_path(@post, comment), remote: true, method: :post, class: 'btn btn-danger' %>
          <% else  %>
            <span class="btn btn-success disabled">↑</span>
            <strong><%= count_rating(comment.votes)%></strong>
            <span class="btn btn-danger disabled">↓</span>
          <% end %>
      <% if comment.author == current_author  %>
    <p>
      <%= link_to 'Destroy', [comment.post, comment], remote: true,
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
                   |
      <%= link_to "Edit", edit_post_comment_path(comment.post, comment), remote: true %>
    </p>
    <% end %>
    <% end %>
    <% unless current_author %>
<strong>Rating: <%= count_rating(comment.votes)%></strong>
<% end  %>
    <br>
    <br>
  </div>

app/views/comments/_form.html.erb
<h2>Add comment  <%= fa_icon "edit" %></h2>
<%= form_for ([@post, @post.comments.build]), remote: true do |f| %>
<%= f.hidden_field :parent_id, value: params[:parent_id] %>
  <p>
    Text<br>
    <%= f.text_area(:body, {:class => "form-control"}) %>
  </p>
  <p>
    <%= f.submit("Add comment",{:class => 'btn btn-success'}) %>
  </p>
<% end  %>

app/views/comments/_form2.html.erb
<div class="container reply_comment_form">
<h2 class="form-header">Add comment  <%= fa_icon "edit" %></h2>
<%= form_for ([@post, @comment]), remote: true do |f| %>
  <p>
    <%= f.hidden_field :parent_id %>
    Text<br>
    <%= f.text_area(:body, {:class => "form-control"}) %>
  </p>
  <p>
    <%= f.submit("Add comment",{:class => 'btn btn-success'}) %>
  </p>
<% end  %>
</div>

app/views/comments/_replies.html.erb
<%= form_with(model: [ @post, @post.comments.build ], local: true) do |form| %>

  <!--# ancestry-->
  <%= form.hidden_field :parent_id, value: params[:parent_id] %>


  <p>
    <%= form.label :comment %><br>
    <%= form.text_area :comment, class:'form-control' %>
  </p>
  <p>
    <%= form.submit class:'btn btn-info btn-lg' %>
  </p>
<% end %>

app/views/comments/create.js.erb
$(".comments").replaceWith("<div class='comments'><%= j nested_comments @post.comments.arrange(order: :created_at)%>")
$('.new_comment')[0].reset();
$(".reply_comment_form").hide(500);

app/views/comments/destroy.js.erb
$(".comment<%=@comment.id %>").hide(500) 

app/views/comments/edit.html.erb
<%= render 'form2' %>

app/views/comments/edit.js.erb
$(".comment<%=@comment.id %>").replaceWith('<div class="form-edit"><%= j render('form2', comment: @comment) %> </div>');
$(".form-header").replaceWith("<h1 class='form-header'>Edit</h1>")
$(".reply-form").hide(500)

app/views/comments/new.html.erb
<div class="container">
  <%= render @comment.parent if @comment.parent %>
  <%= render "form" %>  
</div>

app/views/comments/new.js.erb
$(".reply-form").hide(500)
$(".comment<%=@comment.parent_id %>").after('<div class="reply-form"<%= j render('form2', comment: @comment) %></div>');
$(".form-header").replaceWith("<h1 class='form-header'>Reply</h1>")
//$(".form-edit").hide(500)

app/views/comments/update.js.erb
$(".comment<%=@comment.parent_id %>").after('<%= j render('form2', comment: @comment) %>');