config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  root 'posts#index'

  get 'password_resets/new'
  resources :password_resets

  resources :posts do
    resources :comments do
      resources :votes
      post '/dislikes' => 'votes#dislike', as: :dislike_create
    end
  end

  resources :authors do
    member do
      get :confirm_email
    end
  end
  resources :sessions, only: %i[new create destroy]
  get 'signup', to: 'authors#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
end
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  is_impressionable counter_cache: true
  belongs_to :author
  has_many :comments, dependent: :destroy
  has_one_attached :picture
  validates :title, presence: true, length: { minimum: 4, maximum: 20 }
  validates :content, presence: true
  has_rich_text :content

  def self.search(search)
    where('title ILIKE ? OR plain_text ILIKE ?', "%#{search}%", "%#{search}%")
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  impressionist actions: [:show], unique: [:session_hash]
  before_action :set_post, only: %i[show edit update destroy]
  before_action :correct_author, only: %i[edit update destroy]
  before_action :have_rights?, only: %i[create new edit update destroy]
  before_action :actions_check
  before_action :banned?, only: %i[new create update]

  def correct_author
    @post = Post.find_by(id: params[:id])
    redirect_to root_path(current_author) unless current_author
  end

  def index
    @posts = if params[:search]
               Post.search(params[:search]).order('created_at DESC')
             else
               Post.all.order('created_at DESC')
             end
  end

  def show
    impressionist @post
  end

  def new
    @post = Post.new
  end

  def edit; end

  def create
    @post = Post.new(post_params)
    @post.author = current_author
    @post.plain_text = @post.content.to_plain_text
    respond_to do |format|
      if @post.save
        flash[:success] = 'Post was successfully created.'
        format.html { redirect_to @post }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.js { render 'destroy', status: :destroy, location: @post }
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content, :picture, session[:author_id])
  end

  def actions_check
    cookies[:actions] = if cookies[:actions]
                          cookies[:actions].to_i + 1
                        else
                          0
      end
  end
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
  def current_author?(author)
    author == current_author
  end

  def current_author
    if (author_id = session[:author_id])
      @current_author ||= Author.find_by(id: author_id)
    end
  end
end

app/views/posts/_form.html.erb
<div class="container main">
  <%= form_with(model: post, local: true) do |form| %>
    <% if post.errors.any? %>
      <div class="alert alert-danger">
        <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>
        <ul>
          <% post.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control"%>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.rich_text_area :content, class: "editor"%>
  </div>
      <% # form.label "Picture" %>
      <% # form.file_field :picture %>
      <br>
      <div class="text-center">
  <div class="actions">
    <%= form.submit 'Submit', class: "btn btn-primary" %>
  </div>
  </div>
  <% end %>
</div>

app/views/posts/_post.html.erb
<article class="post<%= post.id %>">
  <section class="post-head">
    <h2><%= link_to post.title, post_path(post) %></h2>
    <small> <% if edited?(post) %>
            <p>edited <%= fa_icon 'edit'%> </p>
            <% end %>
    </small>
    <p><%= post.author.login %></p>
    <p data-toggle="tooltip" data-placement="top" title="Uniq views(<%= post.impressionist_count(:filter=>:ip_address) %>)"> <%= fa_icon "eye" %> Views: <%= post.impressions_count %> <%= fa_icon "comments" %> <%= post.comments.count %><small></p>
      <time data-toggle="tooltip" data-placement="top" title="(<%=post.updated_at  %>)"><%= post.created_at.to_date.strftime("%d %B, %Y") %></time>
      <% if post.author == current_author  %>
        |
        <%= link_to 'Edit', edit_post_path(post) %>
        |
        <%= link_to 'Destroy', post, remote: true,  method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end  %>
    </small>
  </section>

  <section class="post-content">
    <%= sanitize(post.content.to_s[0..100] ) %>
    <%=  image_tag(post.picture) if post.picture.attached? %>
  </section>
</article>
<hr>

app/views/posts/destroy.js.erb
$(".post<%= @post.id %>").hide(500);

app/views/posts/edit.html.erb
<div class="container">
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post, class: "badge badge-primary" %> |

  <%= link_to 'Back', posts_path, class: "badge badge-primary" %>
</div>

app/views/posts/index.html.erb
<div class="container">
  <h1>Posts</h1>
  <%= render @posts %>
</div>

app/views/posts/new.html.erb
<div class="container">
  <h1>New Post</h1>
</div>

<%= render 'form', post: @post %>
<div class="container">
  <%= link_to 'Back', posts_path %>
</div>

app/views/posts/show.html.erb
<div class="container main">
<p>
  <strong>Author:</strong>
  <%= @post.author.login  %>
  <br>
  <small><time><%= @post.created_at.to_date.strftime("%d %B, %Y") %></time></small>
</p>
<div class="page-header">
  <strong><h1><%= @post.title %> </strong><small><% if edited?(@post) %>
          <p>edited <%= fa_icon 'edit'%> </p>
          <% end %></small></h1>
          <% if @post.author == current_author %>
          <%= link_to fa_icon("pencil", text: "Edit"), edit_post_path(@post), class: "btn btn-warning" %>
          <%= link_to fa_icon("trash", text: "Delete" ), @post, method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-danger pull-right"  %>
          <% end %>
</div>
<section class="post-content">
  <%= @post.content %>
</section>
<%=  image_tag(@post.picture) if @post.picture.attached? %>
<br>
<% # link_to 'Back', posts_path, class: "badge badge-warning" %>
<hr>
<h2>Comments</h2>
<div class="comments">
<div class="new_comment_place">
<%= nested_comments @post.comments.arrange(order: :created_at)  %>
</div>
</div>
<hr>
<% if current_author == nil %>
  <p>You must be logged in to post comments.</p>
  <% else %>
<%= render 'comments/form' %>
<% end %>
</div>