config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  root 'posts#index'

  get 'password_resets/new'
  resources :password_resets

  resources :posts do
    resources :comments do
      resources :votes
      post '/dislikes' => 'votes#dislike', as: :dislike_create
    end
  end

  resources :authors do
    member do
      get :confirm_email
    end
  end
  resources :sessions, only: %i[new create destroy]
  get 'signup', to: 'authors#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
end
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectOne</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Posts</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><a href="#">Link</a></li>
          </ul>
          <form class="navbar-form navbar-left">
            <div class="form-group">
              <%= form_tag(posts_path, :method => "get", id: "search-form") do %>
                <%= text_field_tag :search, params[:search], placeholder: "Search Posts", class: "form-control" %>
                <%= submit_tag "Search", class: "btn btn-outline-primary" %>
              <% end %>
                        </div>
              </form>
              <ul class="nav navbar-nav navbar-right">
                <% unless current_author == nil %>
                <li><%= link_to 'New Post', new_post_path%></li>
                <% end %>
                <% if current_author %>
                      <li><%= link_to fa_icon("sign-out", text: "Log Out"), logout_path %></li>
                <% else %>
                  <li><%= link_to fa_icon("sign-in", text: "Sign Up"), signup_path %></li>
                  <li><%= link_to fa_icon("lock", text: "Log In"), login_path %></li>
                <% end %>
              </ul>
            </div><!-- /.container-fluid -->
        </div><!-- /.navbar-collapse -->
        <div class="pull-right">
          <% if current_author %>
          <%= fa_icon "user" %> Logged in as <%= current_author.email %>.
          <% end  %>
        </div>
    </nav>
    <%# if pop_up and current_author == nil %>
      <!--<script>alert('You are not log in. Plz log in or register');</script>-->
    <%# end %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
    </div>
    <%= yield %>
  </body>
</html>